%% Project 259 - CIRS040GSE GPU interpolation-optimized reconstruction

clear;
clc;
close all;

projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));

headerFile = fullfile( ...
    projectRoot, ...
    "data", "raw", "CIRS040GSE", "CIRS040GSE", ...
    "USHEADER_20220330104510.mat");

dataFile = fullfile( ...
    projectRoot, ...
    "data", "raw", "CIRS040GSE", "CIRS040GSE", ...
    "low_attenuation", ...
    "USDATA_20220330104522673.mat");

outputDir = fullfile( ...
    projectRoot, ...
    "data", "processed", "gpu");

if ~exist(outputDir, "dir")
    mkdir(outputDir);
end

outputFile = fullfile( ...
    outputDir, ...
    "cirs040_gpu_interp_optimized_reconstruction.mat");

outputImageFile = fullfile( ...
    outputDir, ...
    "cirs040_gpu_interp_optimized_reconstruction.png");

fprintf("Project 259 - CIRS040GSE interpolation-optimized GPU reconstruction\n");
fprintf("-----------------------------------------------------------------\n");

if gpuDeviceCount == 0
    error("No supported GPU was detected.");
end

gpu = gpuDevice;

fprintf("GPU: %s\n", gpu.Name);
fprintf("Compute capability: %s\n", gpu.ComputeCapability);
fprintf("GPU memory: %.2f GB\n", gpu.TotalMemory / 1e9);

load(headerFile, "USHEADER");
load(dataFile, "USDATA");

fprintf("System: %s\n", USHEADER.system);
fprintf("Transducer: %s\n", USHEADER.transducer);
fprintf("Sampling frequency: %.3f MHz\n", ...
    USHEADER.fs / 1e6);
fprintf("Center frequency: %.3f MHz\n", ...
    USHEADER.fc / 1e6);
fprintf("Sound speed: %.1f m/s\n", USHEADER.c);
fprintf("Element pitch: %.4f mm\n", ...
    USHEADER.pitch * 1e3);
fprintf("Number of angles: %d\n", ...
    numel(USHEADER.xmitAngles));

[numSamples, numElements, ~, numAngles] = size(USDATA);

fprintf("\nRF data size: %s\n", ...
    mat2str(size(USDATA)));
fprintf("RF data type: %s\n", ...
    class(USDATA));

elementX = ...
    ((0:numElements - 1) - ...
    (numElements - 1) / 2) * USHEADER.pitch;

x = linspace( ...
    min(elementX), ...
    max(elementX), ...
    384);

maxDepth = ...
    (numSamples - 1) / USHEADER.fs * ...
    USHEADER.c / 2;

z = linspace(0, maxDepth, 768);

[X, Z] = meshgrid(x, z);

fprintf("\nImage size: %d x %d\n", ...
    size(X, 1), size(X, 2));

fprintf("Maximum depth: %.2f mm\n", ...
    maxDepth * 1e3);

fprintf("\nPreparing GPU data...\n");

rfGPU = gpuArray(single(USDATA));

XGPU = gpuArray(single(X));
ZGPU = gpuArray(single(Z));

elementXGPU = gpuArray(single(elementX));

sampleTimeGPU = gpuArray(single( ...
    (0:numSamples - 1) / USHEADER.fs));

soundSpeed = single(USHEADER.c);

imageRFGPU = gpuArray.zeros( ...
    size(X), ...
    "single");

fprintf("Starting interpolation-optimized GPU beamforming...\n");

wait(gpuDevice);
startTime = tic;

for angleIndex = 1:numAngles

    angleDeg = USHEADER.xmitAngles(angleIndex);
    angleRad = deg2rad(angleDeg);

    fprintf("Angle %d/%d: %.3f degrees\n", ...
        angleIndex, ...
        numAngles, ...
        angleDeg);

    rfAngle = rfGPU(:, :, 1, angleIndex);

    txTime = ...
        (XGPU .* sin(single(angleRad)) + ...
         ZGPU .* cos(single(angleRad))) ...
        / soundSpeed;

    angleImageGPU = gpuArray.zeros( ...
        size(X), ...
        "single");

    for elementIndex = 1:numElements

        elementPosition = ...
            elementXGPU(elementIndex);

        rxDistance = sqrt( ...
            (XGPU - elementPosition).^2 + ...
            ZGPU.^2);

        totalTime = ...
            txTime + ...
            rxDistance / soundSpeed;

        channelRF = ...
            rfAngle(:, elementIndex);

        receivedSignal = interp1( ...
            sampleTimeGPU, ...
            channelRF, ...
            totalTime, ...
            "linear", ...
            0);

        angleImageGPU = ...
            angleImageGPU + receivedSignal;
    end

    imageRFGPU = ...
        imageRFGPU + angleImageGPU;
end

wait(gpuDevice);

reconstructionTime = toc(startTime);

fprintf("\nGPU beamforming finished.\n");
fprintf("Interpolation-optimized reconstruction time: %.4f seconds\n", ...
    reconstructionTime);

imageRFGPU = ...
    imageRFGPU / ...
    single(numAngles * numElements);

fprintf("\nGenerating B-mode image...\n");

bModeStart = tic;

imageRF = gather(imageRFGPU);

analyticImage = hilbert(imageRF);

envelope = abs(analyticImage);

envelope = ...
    envelope / ...
    (max(envelope(:)) + eps);

bMode = ...
    20 * log10(envelope + eps);

dynamicRange = 60;

bModeDisplay = ...
    max(bMode, -dynamicRange);

bModeProcessingTime = toc(bModeStart);

fprintf("B-mode processing time: %.4f seconds\n", ...
    bModeProcessingTime);

fprintf("\nSaving reconstruction...\n");

save(outputFile, ...
    "bMode", ...
    "bModeDisplay", ...
    "imageRF", ...
    "x", ...
    "z", ...
    "USHEADER", ...
    "reconstructionTime", ...
    "bModeProcessingTime", ...
    "-v7.3");

figure("Visible", "off");

imagesc( ...
    x * 1e3, ...
    z * 1e3, ...
    bModeDisplay);

axis image;
colormap gray;
colorbar;
clim([-dynamicRange 0]);

xlabel("Lateral position (mm)");
ylabel("Depth (mm)");

title("Project 259 - CIRS040GSE GPU Reconstruction");

exportgraphics( ...
    gcf, ...
    outputImageFile, ...
    "Resolution", 150);

close(gcf);

fprintf("\nInterpolation-optimized GPU reconstruction finished.\n");
fprintf("Saved data: %s\n", outputFile);
fprintf("Saved image: %s\n", outputImageFile);