%% Project 259 - CIRS040GSE GPU interpolation-optimized validation

clear;
clc;
close all;

projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));

referenceFile = fullfile( ...
    projectRoot, ...
    "data", "processed", ...
    "gpu", ...
    "cirs040_gpu_reconstruction.mat");

optimizedFile = fullfile( ...
    projectRoot, ...
    "data", "processed", ...
    "gpu", ...
    "cirs040_gpu_interp_optimized_reconstruction.mat");

outputDir = fullfile( ...
    projectRoot, ...
    "data", "processed", ...
    "validation");

if ~exist(outputDir, "dir")
    mkdir(outputDir);
end

outputFile = fullfile( ...
    outputDir, ...
    "cirs040_gpu_interp_optimized_comparison.mat");

differenceImageFile = fullfile( ...
    outputDir, ...
    "cirs040_gpu_interp_optimized_difference.png");

fprintf("Project 259 - CIRS040GSE GPU interpolation-optimized validation\n");
fprintf("--------------------------------------------------------------\n");

if ~isfile(referenceFile)
    error("Validated GPU reconstruction was not found: %s", ...
        referenceFile);
end

if ~isfile(optimizedFile)
    error("Optimized GPU reconstruction was not found: %s", ...
        optimizedFile);
end

reference = load(referenceFile);
optimized = load(optimizedFile);

referenceRF = double(reference.imageRF);
optimizedRF = double(optimized.imageRF);

fprintf("\nRF image size\n");
fprintf("----------------\n");
fprintf("Validated GPU: %s\n", ...
    mat2str(size(referenceRF)));

fprintf("Optimized GPU: %s\n", ...
    mat2str(size(optimizedRF)));

if ~isequal(size(referenceRF), size(optimizedRF))
    error("RF image sizes do not match.");
end

difference = ...
    optimizedRF - referenceRF;

absoluteDifference = ...
    abs(difference);

maximumAbsoluteError = ...
    max(absoluteDifference(:));

meanAbsoluteError = ...
    mean(absoluteDifference(:));

relativeL2Error = ...
    norm(difference(:)) / ...
    (norm(referenceRF(:)) + eps);

referenceVector = referenceRF(:);
optimizedVector = optimizedRF(:);

referenceCentered = ...
    referenceVector - mean(referenceVector);

optimizedCentered = ...
    optimizedVector - mean(optimizedVector);

correlationNumerator = ...
    sum(referenceCentered .* optimizedCentered);

correlationDenominator = ...
    sqrt(sum(referenceCentered.^2) * ...
    sum(optimizedCentered.^2));

correlationCoefficient = ...
    correlationNumerator / ...
    (correlationDenominator + eps);

fprintf("\nRF comparison results\n");
fprintf("---------------------\n");

fprintf("Maximum absolute error: %.6e\n", ...
    maximumAbsoluteError);

fprintf("Mean absolute error:    %.6e\n", ...
    meanAbsoluteError);

fprintf("Relative L2 error:      %.6e\n", ...
    relativeL2Error);

fprintf("Correlation coefficient: %.9f\n", ...
    correlationCoefficient);

referenceBMode = double(reference.bMode);
optimizedBMode = double(optimized.bMode);

bModeDifference = ...
    optimizedBMode - referenceBMode;

maximumBModeError = ...
    max(abs(bModeDifference(:)));

meanBModeError = ...
    mean(abs(bModeDifference(:)));

fprintf("\nB-mode comparison results\n");
fprintf("-------------------------\n");

fprintf("Maximum absolute error: %.6e dB\n", ...
    maximumBModeError);

fprintf("Mean absolute error:    %.6e dB\n", ...
    meanBModeError);

fprintf("\nTiming comparison\n");
fprintf("-----------------\n");

fprintf("Validated GPU time: %.4f seconds\n", ...
    reference.reconstructionTime);

fprintf("Optimized GPU time: %.4f seconds\n", ...
    optimized.reconstructionTime);

speedup = ...
    reference.reconstructionTime / ...
    optimized.reconstructionTime;

fprintf("Speedup: %.3fx\n", speedup);

figure("Visible", "off");

imagesc( ...
    optimized.x * 1e3, ...
    optimized.z * 1e3, ...
    difference);

axis image;
colormap gray;
colorbar;

xlabel("Lateral position (mm)");
ylabel("Depth (mm)");

title("Validated GPU - Interpolation-Optimized GPU Difference");

exportgraphics( ...
    gcf, ...
    differenceImageFile, ...
    "Resolution", 150);

close(gcf);

save(outputFile, ...
    "maximumAbsoluteError", ...
    "meanAbsoluteError", ...
    "relativeL2Error", ...
    "correlationCoefficient", ...
    "maximumBModeError", ...
    "meanBModeError", ...
    "speedup", ...
    "-v7.3");

fprintf("\nSaved comparison data: %s\n", ...
    outputFile);

fprintf("Saved difference image: %s\n", ...
    differenceImageFile);

fprintf("\nGPU interpolation-optimized validation finished.\n");